name: Pythonia meetup

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: noti_pythonia_weekly
      working-directory: ./utils
      env:
        PYCON_CALENDAR_ID: ${{ secrets.PYCON_CALENDAR_ID }}
        ZOOM_LINK: ${{ secrets.ZOOM_LINK }}
        PYCON_WEEKLY_DOC_URL: ${{ secrets.PYCON_WEEKLY_DOC_URL }}
        PYCON_ICON_URL: ${{ secrets.PYCON_ICON_URL }}
        SLACK_WEB_HOOK: ${{ secrets.SLACK_WEB_HOOK }}
        GOOGLE_SERVICE_ACCOUNT_JSON_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_KEY }}
      run: |
        python noti_pythonia_weekly.py
